# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Xcode Select Version
      uses: mobiledevops/xcode-select-version-action@v1
      with:
          xcode-select-version: 14.2
    - name: Build
      run: xcodebuild clean build -project iOS/Village/Village.xcodeproj -scheme Village -destination 'platform=iOS Simulator,name=iPhone 13, OS=latest'
      
