# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:

    runs-on: macos-13-xlarge

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
    - uses: actions/checkout@v3
    - name: Start xcode build
      run: |
        xcodebuild clean test -project iOS/Village/Village.xcodeproj \
        -scheme Village \
        -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=latest' \
        -skipPackagePluginValidation \
        -allowProvisioningUpdates
